import type { Metadata } from "next";
import "./globals.css";
import Header from "../components/Header";
import { Rakkas, Raleway } from "next/font/google";



const rakkas_font = Rakkas({
  subsets: ['latin'],
  weight: [ '400'],
  variable: "--font-rakkas",
});

const raleway_font = Raleway({
  subsets: ['latin'],
  weight: [ '400'],
  variable: "--font-raleway",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      
      <body
        className={`${rakkas_font.variable} ${raleway_font.variable} min-h-screen flex flex-col`}
      >
       {/* Toaster*/}

    <header className="border-b sticky top-0 bg-white z-50">
      <Header />
    </header>    

        
        <div className="flex-1 w-full">
         <main>{children} </main> 
         </div>


      </body>
    </html>
  );
}
